### ISSUE TITLE
Too Many Eclipse Plugin Repositories

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TeamMentor_Eclipse_Plugin#10]
There are too many Eclipse Plugin repositories. It is confusing and unnecessary. 
Also we should be tracking these issues in TeamMentor/Master as this plugin is a TM 3.5 release (so far) and it is confusing to have multiple issue lists.

**Comment by DinisCruz** [comment]
I actually prefer to have the issues here, since they are easier to manage and read them all in one go (like what I'm doing now).

At the moment there are 3 Eclipse repos and I might actually need to add a 4th one :), so there are not that many :)

This is another of of those GitHub org limitations, since ideally this should be managed like an organization (i.e. separate repos and issues for this particular topic/code (the fortify plug-ins))

**Comment by romichg** [comment]
Where to track issues question aside, why do we need 4 Repos for one Project? I don't buy that this is a github limitation. With one Repo used for Eclipse Plugin, what is the other 3 used for?

**Comment by DinisCruz** [comment]
At the moment I'm using these 4 repos:
- https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin : Eclipse Plugin project with source code
- https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin_Build : Eclipse Update site project with binaries (i.e jars (which should never be placed in the same place as the main source code)). Note that this is the repo that is pushed to Azure (or any HTTP server) and which behaves like an 'update site' (i.e. the url that is used to install/update from eclipse, is the root of this repo). this repo also allows for offline installs
- https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin_Build - SWTBot project, which is maven driven and is used by the CI Jenkins server to auto create the distribution jars (without any user intervention)
- https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin_Modules : currently place holder for the idea that I was exploring of having extra functionality delivered as eclipse projects  

And btw, checkout how many repos Jenkins has: https://github.com/jenkinsci/ (they basically have a repo per plug-in) :)

**Comment by romichg** [comment]
Ok, so can we follow the same convention as we do for TeamMentor?  Teammentor_Eclipse_Plugin_Dev and TeamMentor_Eclipse_Plugin_Release?

**Comment by DinisCruz** [comment]
That would create even more repos :)

At the moment the Release and Dev if the main plugin are tracked as branches

**Comment by romichg** [comment]
Not really. We would just rename TeamMentor_Eclipse_Plugin to TeamMentor_Eclipse_Plugin_Dev  and TeamMentor_Eclipse_Plugin_Build to TeamMentor_Eclipse_Plugin_Release
The other two I am still confused about. Why does SWTBot project need a repo? Is this the code and configuration for the SWTBot, then it should be called as SWTBot  :)

**Comment by DinisCruz** [comment]
That _Build are the actual binaries, where our _Release is the current
release commit of _Dev

Completely different things

The _Build is the code that automates the build (which amongst other things
uses the SWtBot api)
