### ISSUE TITLE
TeamMentor menu should not have "Write TM Script" as an option

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TeamMentor_Eclipse_Plugin#13]
This is more of a developer/debug feature. Instead we should have a "settings" page where a user can tick "enable development options" which would make this and any other development use menus available.

**Comment by DinisCruz** [comment]
(Ignore last comment since it was placed on the wrong issue :)  )

This is actually a very useful feature and one that I thing a good number of our more advanced users will make good use of.

But I agree that the menu title is not very good, so I changed it to "Util - Write Script (TeamMentor DSL)"

**Comment by romichg** [comment]
Again, I think this should be in the properties page in some advanced section. It is confusing for it to be on the main UI Menu.

**Comment by tlaloc75** [comment]
Agreed, keep it simple.

**Comment by romichg** [comment]
This is fixed.
