### ISSUE TITLE
The default TM window should be wider. 

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TeamMentor_Eclipse_Plugin#14]
Right now, it just seems to narrow compared to the left pane.

**Comment by DinisCruz** [comment]
There is not a lot we can do since this is controlled by the user (i.e the user is the one that controls the size of those views)

**Comment by romichg** [comment]
But doesn't the size of the window depends on the properties of the
perspective? Can't we change that?

**Comment by romichg** [comment]
It really doesn't look nice. Even the TeamMentor logo is not completely displayed.
