### ISSUE TITLE
Proper license should be displayed on the TM Plugin Install page

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TeamMentor_Eclipse_Plugin#15]

**Comment by DinisCruz** [comment]
Which one should I use? at the moment we don't have a good 'text only' version. Should I point it to a URL?

**Comment by romichg** [comment]
I think this is a question for Jason. Can you copy the one we use for TeamMentor? Or what about the one we had for cat.net integration?

**Comment by tlaloc75** [comment]
Send both to the alias and we'll see which one works.

**Comment by romichg** [comment]
Dinis, do you have the license used for Cat.Net?

**Comment by DinisCruz** [comment]
I ended up using the same license we had on the Cat.net plug-in. I was in RTF format, so I just did a a copy and paste into text format (which looked ok)

You can see the change here (and the text): https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/commit/35b16d4956b5c34428c7b8aaa5469a50711de00b
