### ISSUE TITLE
There should be an easy way to point to a different TeamMentor Instance

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TeamMentor_Eclipse_Plugin#17]
Right now the plugin points to teammentor.net. For customers hosting their own instance of TM, there is no easy way to set the plugin to point to their local instance of TM. There should be a settings section where this can be changed.

**Comment by DinisCruz** [comment]
Implemented in 1.3.1 (with new Preferences page)

**Comment by romichg** [comment]
This is not fully fixed because of - https://github.com/TeamMentor/Master/issues/648

**Comment by DinisCruz** [comment]
Fixed with: https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/commit/8db16484f518da36129684d907e03b19f193cc96#diff-d4b6cbfa458cba5cf873f65212000ae7R37
