### ISSUE TITLE
Use TeamMentor Icons and not Eclipse default icons

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TeamMentor_Eclipse_Plugin#18]

**Comment by DinisCruz** [comment]
Done on 1.3.1

**Comment by romichg** [comment]
I don't see the TM Icons. Any place in particular I should look for?

**Comment by DinisCruz** [comment]
see the little icons that show up on top of the TM views:

![image](https://f.cloud.github.com/assets/656739/1412897/c0007512-3df9-11e3-8bb7-44816027257f.png)

**Comment by romichg** [comment]
aaah. ok. Now I see it :)
