### ISSUE TITLE
Create the beta version for release 1.3.4

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TeamMentor_Eclipse_Plugin#19]
Change the defaults to use Vulnerabilities.teammentor.net with no login token

**Comment by DinisCruz** [comment]
This is now done where if you start with a clean instance of Eclipse (with Groovy Plugin) and use the update site https://tm-eclipse-plugin.azurewebsites.net , you will get the version 1.3.4 strait away 

This is important because this way, the latest version is the one installed, which is not the case for the 1.3.4.NNNN versions, which require an extra 'update' to be installed.

**Comment by romichg** [comment]
Ok I am confused here. I did an Update of the existing version and I uninstalled a fresh copy of everything and in both cases it installed  1.3.4.201310260624 so what do you mean here?

**Comment by DinisCruz** [comment]
That is correct, and you're getting the latest version

Without the 1.3.4 version bump, you would get on a fresh install the first
version of 1.3.3 and not the last published one

**Comment by romichg** [comment]
Oh ok. I was just confused by your NNNN comments... Thanks. This is now fixed.
