### ISSUE TITLE
Fix 32bit Deployment Issue

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TeamMentor_Eclipse_Plugin#3]
current version only work in 64bit

**Comment by DinisCruz** [comment]
The latest dev build was all created in 32bit and that works ok

This will need to be automated as part of the CI build (see https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/issues/5 ) and my question is how to automate the creation of the multiple versions

**Comment by romichg** [comment]
This is still an issue. Can't install on 32 Bit system

**Comment by DinisCruz** [comment]
try now with the version 1.3.3

**Comment by DinisCruz** [comment]
Roman, in cases like this where there are two issues opened, I'm closing this ones here (on this repo) and leaving the other one opened: https://github.com/TeamMentor/Master/issues/633
