### ISSUE TITLE
Create CI (Continuous Integration) setup for plug-in 

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TeamMentor_Eclipse_Plugin#5]
With full automation of:
- eclipse plugin compilation
- feature and update site creation
- UnitTes
- push to Azure
- 32bit and 64bit

Ideally allow direct downloads of packaged eclipsed versions (with no need to do any plugin installs (before started using the Eclipse Plug in))

**Comment by romichg** [comment]
I dont' think this is necessary for the Beta

**Comment by DinisCruz** [comment]
OK, finally I have the first full loop of Continuous Integration working :)

Here is the current workflow

1) developer (me) makes a change on the source code (for example a small one like this one:  https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/commit/6a2a86f13754ebdf915230763c4ad3940c1abc3f)
2) code is committed to the local fork
3) code is pushed to GitHub

--- the next steps happen all automatically

4) Jenkins is monitoring the GitHub repo (https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin), and in less than 1 minute will detect a change
5) https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin will be cloned locally
6) once the clone completes , another Jenkins job is triggered which will execute the following SWTBot automation from the https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin_Deploy repo:
  a) it all starts with: mvn clean   (to clean the current target)
  b) then there are a number of eclipse jar dependencies that need to be copied to the Jenkins workspace (target/work/plugins) which I was not able to figure out how to get them there using tycho (the code is done using a Groovy script written in Jenkin's UI)
  c) now the heavy lifting happens with the SWBot script being executed using mvn integration-test
7) the integration test is basically the UI automation of the creation of the https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin in eclipse (since eclipse knows how to build this plugin :)  )
8) once the process is completed (i.e. the projects are added to eclipse, the plugin is built, and the update Site is rebuilt), a local clone of https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin_Build will now contain the updated Jar (note that this is already the Eclipse update site)
---- All the steps above happened in an automated way

9) on a separate box/vm, I now open another instance of Eclipse and either:
   a) install the plug 
   b) update the plug-in (this one is quite fast)

This is really powerful since for the first time I have a fully automated Eclipse plugin creation workflow (where the only manual steps are the commit/push of the code changes and the update into the new version)

Note that the recommended workflow is to do all changes on branches and use GitHubs Pull Requests to bring the changes into the master/next_release branch

**Comment by DinisCruz** [comment]
This is now basically done. What Is needed next to document it better and do incremental changes. 

But the hard part is done (and it took me almost two weeks of effort to pull it off). In fact, there were moments that I felt I was doing heart surgery, give the complexity and moving parts that I was having to deal with

**Comment by romichg** [comment]
Good job man!
