### ISSUE TITLE
Add Groovy dependencies to TM Plugin install

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TeamMentor_Eclipse_Plugin#6]
The objective is that we only require the installation of one plugin

**Comment by DinisCruz** [comment]
almost there

will be part of the automated build:  https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/issues/5

**Comment by romichg** [comment]
I don't think this is necessary for Beta

**Comment by DinisCruz** [comment]
Done
