### ISSUE TITLE
We need a proper SSO solution - TeamMentor is currently asking user for sessionID

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TeamMentor_Eclipse_Plugin#9]
It looks like teammentor.net user is hard coded in the plugin. Again and again we are not practicing what we preach. 
https://www.teammentor.net/article/d0a40ac5-a11c-4797-bd6f-94a9d7c881f9
https://www.teammentor.net/article/8ce6a31c-076b-4c6a-840c-79c08250c994

Are some of the articles that state NOT to hard code user credentials. Besides being a bad security practice, It sets a bad example and a bad precedence.

**Comment by DinisCruz** [comment]
OK, so what is the solution? Ask the user to login and save its token
somewhere locally?

The current solution is equivalent to shipping an API key with an app.
Which I agree is not ideal, but it is simple(r) to implement

Note that with the currently plug-in we can disable that session access
independently at teammentor.net server

**Comment by romichg** [comment]
Solution would be to ask the user for credentials (once at install) authenticate and save the random per user session key. Also giving the user the option to change the username/pw used for TM.net in the Settings page.  This way we authenticate the user, and keep track of their history.

**Comment by romichg** [comment]
This is related to https://github.com/TeamMentor/Master/issues/586

**Comment by DinisCruz** [comment]
At the moment in 1.3.1 the user can set its SessionID via the properties page. Which is a step on the right direction.

So are you saying that we should ask all users of the plug-in to authenticate? (at lease the first time they use TeamMentor?).

**Comment by romichg** [comment]
Assuming the user has teammentor.net credentials, we should ask them for
what they know. If we choose to store the sessionID and not the password we
need to treat it as if it was a password - i.e. keep it encrypted on the
client side under tight access controls. We should also be careful about a
logout issue that Michael brought up. If the user opens up
teammentor.netin an eclipse window, there is a potential for him/her
to click the logout
button. This will invalidate the session and lockout the user.

**Comment by tlaloc75** [comment]
For fortify connection to vulns server, we need nothing - it is open to anon. For connection from vuln to TM.NET we should ask for uname and pwd. For connection from plugin to a self-hosted server we should allow anon, uname/pwd login, sso or AD integration as per the customer's preference.

Jason

**Comment by romichg** [comment]
So currently for vuln to TM.NET we just bring up a login popup. There is no way for user to signup or be guided to signup. This is issue: https://github.com/TeamMentor/Master/issues/618  Will this be an issue for customers, or is this just a nice to have? The fix would actually be in teammentor.net code.

**Comment by tlaloc75** [comment]
I think a simple link to the main TM UI, in a new browser window, would be a good idea, so that the user can pop out and sign up.  This will really only cover the eval scenario, so its not necessary for this release, just nice to have. Is there currently a forgot password link in the dlg? That will be necessary for the paid customer scenario. Would also be nice to have an email link for support alias in case they are having problems.

**Comment by romichg** [comment]
Yes it brings up a regular login dialog with password reset.  I think in the future we should bring back the page that said - This requires a login, click here to login here to sign up and here for support. Like we had in 3.3.

**Comment by tlaloc75** [comment]
Yes I agree

**Comment by DinisCruz** [comment]
This commit makes the plugin default to be vulnerabilities.teammentor.net with an empty GUID as its sessionID: https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/commit/baebc03dc7f8156b73a00ad4ca04132f16ec600f

**Comment by romichg** [comment]
This should not be closed. I just updated the title to remove the "Session Hardcoded in Plugin" as we are now asking user for the sessionID. But we still need a solution. We don't need this for Beta (as it points to vulnerabilities.teammentor.net, but I think we need this for release)

**Comment by DinisCruz** [comment]
Roman, the latest SSO solution addresses this right?

**Comment by romichg** [comment]
Yes this can be closed.
